---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Copy Dockerfile and index.html
      copy:
        src: /home/user/hostsite/Dockerfile
        dest: /tmp/Dockerfile

    - name: Build Docker image
      command: docker build -t sample-webpage /tmp

    - name: Run Docker container
      docker_container:
        name: sample-webpage-container
        image: sample-webpage
        ports:
          - "85:85"
        state: started
